Repository vtexdocs/components, pull requests merged in 2024-10, with the labels that each got.

#26 feat/sidebar localized slugs
  dist/index.css
  dist/index.css.map
  dist/index.d.mts
  dist/index.mjs
  dist/index.mjs.map
  package.json
  src/components/sidebar-elements/index.tsx
  yarn.lock
Labels: release-patch

#27 Update translations
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
Labels: release-no

#24 feat/links match new accessibility needs
  src/lib/markdown-renderer/styles.module.css
Labels: release-minor
