Repository vtexdocs/components, pull requests merged in 2025-01, with the labels that each got.

#32 Fix localized strings
  dist/index.css.map
  dist/index.mjs
  dist/index.mjs.map
  src/components/sidebar-section/index.tsx
Labels: release-minor

#33 Minor release because the previous (localized strings) failed
  src/components/sidebar-section/index.tsx
Labels: release-minor

#34 Release localized version
  src/components/sidebar-section/index.tsx
Labels: release-major

#35 Update release-version.yml
  .github/workflows/release-version.yml
Labels: release-no
